### ISSUE TITLE
Criar uma logo charmosa

### ISSUE THREAD

**Issue by IgorHalfeld** [IgorHalfeld/pr-maneiro#15]

**Comment by xReee** [comment]
Posso fazer? :D

**Comment by delley** [comment]
@xReee já tava até mandando um PR...

**Comment by xReee** [comment]
@delley se o teu tiver pronto pode mandar, ainda não comecei

**Comment by delley** [comment]
@xReee blz...

**Comment by IgorHalfeld** [comment]
https://github.com/IgorHalfeld/pr-maneiro/pull/16

![image](https://user-images.githubusercontent.com/9022134/66413690-3e57ff80-e9ce-11e9-9b83-a49dd457d339.png)
