### ISSUE TITLE
Campo Select dos templates vazio

### ISSUE THREAD

**Issue by rhuangabrielsantos** [IgorHalfeld/pr-maneiro#40]
Após a aprovação do pull request #37, o select dos templates sempre fica vazio

![image](https://user-images.githubusercontent.com/50742592/70375624-8c11bb00-18de-11ea-94be-9574e942ca08.png)

![image](https://user-images.githubusercontent.com/50742592/70375628-a6e42f80-18de-11ea-8f61-83c23131522d.png)

**Comment by IgorHalfeld** [comment]
Consegue verificar de novo? aqui tá normal @rhuangabrielsantos

**Comment by IgorHalfeld** [comment]
Qualquer coisa já coloco no #43

**Comment by rhuangabrielsantos** [comment]
Eu clonei o projeto novamente, e continua com o problema, eu uso o navegador Brave, que é baseado no chromium, será que é por isso? @IgorHalfeld

**Comment by IgorHalfeld** [comment]
Testa o seguinte, faz o `git fetch && git checkout v1.0` pra ir pra branch `v1.0` que é a que tá no PR #43 
Essa branch tá quase toda finalizada, só falta eu terminar os testes

**Comment by rhuangabrielsantos** [comment]
Deve ser algum bug nesse navegador, segue print abaixo:

![image](https://user-images.githubusercontent.com/50742592/71284357-5094d900-2341-11ea-816d-73ba19eff02a.png)

**Comment by IgorHalfeld** [comment]
Megeei o #43 e baixei o brave pra testar aqui

![image](https://user-images.githubusercontent.com/9022134/71315361-946b0980-2439-11ea-92bb-61553555004d.png)

Mas tá rolando, você tá na ultima versão do brave?

**Comment by IgorHalfeld** [comment]
rolou? @rhuangabrielsantos ?

**Comment by rhuangabrielsantos** [comment]
@IgorHalfeld infelizmente não :( , não faço ideia do por que está acontecendo isso, caso aconteça com mais alguém nós vemos o pq ta com esse problema
