### ISSUE TITLE
Bloqueio de imagens

### ISSUE THREAD

**Issue by TCsTheMechanic** [IgorHalfeld/pr-maneiro#42]
As imagens de dois personagens:
- Professor Raimundo
- Padre Marcelo Rossi

Estão tendo acesso negado pelo Chrome na hora de baixar:
![Capturar](https://user-images.githubusercontent.com/22171153/71018732-ca298e80-20d7-11ea-85e0-5c2840e0cb67.PNG)

Além de carregarem somente pela metade no preview:
![Capturar0](https://user-images.githubusercontent.com/22171153/71018778-e1687c00-20d7-11ea-9e83-d36db9630ec1.PNG)

**Comment by IgorHalfeld** [comment]
Hmm, vou trocar, é bom começar a pedir a galera pra sempre subir num [imgur](https://imgur.com/)

**Comment by IgorHalfeld** [comment]
Vou colocar no #43

**Comment by TCsTheMechanic** [comment]
Verdade, vou procurar a img do Kid no imgur aqui pq também está dando este problema.
