### ISSUE TITLE
Adicionar suporte a dark mode

### ISSUE THREAD

**Issue by IgorHalfeld** [IgorHalfeld/pr-maneiro#79]
Usar o [tailwindcss-dark-mode](https://github.com/ChanceArthur/tailwindcss-dark-mode)

_Deve se basear na branch `next` que é onde esta a v2 beta_

**Comment by luizcieslak** [comment]
Estava querendo testar esse plugin do tailwind, vou subir um PR

**Comment by IgorHalfeld** [comment]
@luizcieslak acho que nem precisa de um botão pra dar switch pro dark mode, dá pra pegar do sistema da pessoa essa config, que que cê acha?

**Comment by luizcieslak** [comment]
@IgorHalfeld dá sim mano, pela media-query `prefer-colors-scheme` que pega a config do sistema, justamente o que o [tailwind-css-mode](https://github.com/ChanceArthur/tailwindcss-dark-mode/blob/master/prefers-dark.js#L2) faz por padrão. Lendo a doc deles, eu entendi que também dá pra fazer via um botão se vc colocar/remover o selector `.mode-dark`. Enfim, posso começar o PR usando o padrão e depois vemos se é viavel colocar um switch na barra de navegação, qq c acha?
