### ISSUE TITLE
Adicionar scroll nas opções de templates

### ISSUE THREAD

**Issue by Pedro-Souza** [IgorHalfeld/pr-maneiro#90]
Hoje quando é digitado `a` ele lista todas as opções, mas como são muitas isso quebra o layout. Uma possível solução seria adicionar um scroll. O que acha?

Problema:
![image](https://user-images.githubusercontent.com/10675595/110225357-c42df200-7ec3-11eb-90cd-fa4f947f63ee.png)

Com scroll:
![image](https://user-images.githubusercontent.com/10675595/110225372-e6277480-7ec3-11eb-978f-61c5c579e946.png)

**Comment by IgorHalfeld** [comment]
merged #95
